### PR TITLE
feat(query): Support rename dictionary ddl.

### PR DESCRIPTION
**Pull request by Winnie-Hong0927**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

We implement the logical plan and binder of rename dictionary, and we can call the interface of meta to rename dictionary.
We can execute Dictionary-related SQL statements like follows.
`RENAME DICTIONARY [db0.]dict_A TO [db1.]dict_B;`

- part of: https://github.com/databendlabs/databend/issues/16752

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/16754)

### CODE REVIEW

**Review by drmingdrmer — CHANGES_REQUESTED** [review]
> Reviewed 9 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/databendlabs/databend/16754)* status: 9 of 27 files reviewed, 6 unresolved discussions (waiting on @Winnie-Hong0927)

___
*[`src/meta/app/src/app_error.rs` line 902 at r1](https://reviewable.io/reviews/databendlabs/databend/16754#-OAgQFLW9c5tEN7PtYTH:-OAgQFLW9c5tEN7PtYTI:b3zidi) ([raw file](https://github.com/databendlabs/databend/blob/6783212dbed36dab5d043f4242e08f0c93345c3d/src/meta/app/src/app_error.rs#L902)):*
> ```XML
> #[derive(thiserror::Error, Debug, Clone, PartialEq, Eq)]
> #[error("UnknownDictionary: `{dictionary_name}` while `{context}`")]
> pub struct UnknownDictionary {
> ```

Define Unknown error with `UnknownError`: https://github.com/datafuselabs/databend/blob/af5fe4c3384b220555a282a0c2e33b564d75e43c/src/meta/app/src/tenant_key/errors.rs#L106

Refer to

https://github.com/datafuselabs/databend/blob/10d54aec1e67bdc88f0a4d5e67d0c88b579ec941/src/meta/app/src/app_error.rs#L1033

So does to the `exists` error.
___
*[`src/meta/app/src/schema/dictionary.rs` line 179 at r1](https://reviewable.io/reviews/databendlabs/databend/16754#-OAgPUYnAA3l88B5qnsZ:-OAgPUYnAA3l88B5qns_:b-1fqp6d) ([raw file](https://github.com/databendlabs/databend/blob/6783212dbed36dab5d043f4242e08f0c93345c3d/src/meta/app/src/schema/dictionary.rs#L179)):*
> ```XML
> #[derive(Clone, Debug, PartialEq, Eq)]
> pub struct RenameDictionaryReq {
>     pub if_exists: bool,
> ```

remove this field `if_exists`. This field does not affect catalog or meta-service behavior, it just affect what to respond to the user. Move these logic to corresponding Binder or Interpreter level.
___
*[`src/meta/app/src/schema/dictionary.rs` line 181 at r1](https://reviewable.io/reviews/databendlabs/databend/16754#-OAgQb2aCt7qNQ8-Dxxe:-OAgQb2aCt7qNQ8-Dxxf:b-1884b4) ([raw file](https://github.com/databendlabs/databend/blob/6783212dbed36dab5d043f4242e08f0c93345c3d/src/meta/app/src/schema/dictionary.rs#L181)):*
> ```XML
>     pub if_exists: bool,
>     pub name_ident: DictionaryNameIdent,
>     pub new_db_name: String,
> ```

DictionaryNameIdent does not include a db-name, the target db should be identified by database-id.
___
*[`src/meta/app/src/schema/dictionary.rs` line 219 at r1](https://reviewable.io/reviews/databendlabs/databend/16754#-OAgQvwf4v26CgMQB_Nh:-OAgQvwf4v26CgMQB_Ni:b-y9fs3h) ([raw file](https://github.com/databendlabs/databend/blob/6783212dbed36dab5d043f4242e08f0c93345c3d/src/meta/app/src/schema/dictionary.rs#L219)):*
> ```XML
> /// The meta-service key for storing dictionary id history ever used by a dictionary name
> #[derive(Clone, Debug, Eq, PartialEq, Hash)]
> pub struct DictionaryIdHistoryIdent {
> ```

If Dictionary does not need to support undrop, remove this struct.
___
*[`src/meta/app/src/schema/dictionary.rs` line 231 at r1](https://reviewable.io/reviews/databendlabs/databend/16754#-OAgR49L9WOJ5i5GaK9C:-OAgR49L9WOJ5i5GaK9D:bxzom6j) ([raw file](https://github.com/databendlabs/databend/blob/6783212dbed36dab5d043f4242e08f0c93345c3d/src/meta/app/src/schema/dictionary.rs#L231)):*
> ```XML
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq)]
> pub struct DictionaryIdToName {
> ```

Why is this this identifier required? Is lookup dictionary name by id required?
___
*[`src/query/service/src/interpreters/interpreter_dictionary_rename.rs` line 66 at r1](https://reviewable.io/reviews/databendlabs/databend/16754#-OAgS4ZJDhxsk9mplNi8:-OAgS4ZJDhxsk9mplNi9:bunjctb) ([raw file](https://github.com/databendlabs/databend/blob/6783212dbed36dab5d043f4242e08f0c93345c3d/src/query/service/src/interpreters/interpreter_dictionary_rename.rs#L66)):*
> ```XML
>                 ),
>                 new_db_name: self.plan.new_database.clone(),
>                 new_dictionary_name: self.plan.new_dictionary.clone(),
> ```

The target should also be a `DictionaryIdToName`, instead of db-name plus a dictionary name.



_Code quote:_
```XML
                new_db_name: self.plan.new_database.clone(),
                new_dictionary_name: self.plan.new_dictionary.clone(),
```

**Review by drmingdrmer — CHANGES_REQUESTED** [review]
> Reviewed 8 of 27 files at r1, 10 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/databendlabs/databend/16754)* status: 27 of 31 files reviewed, 6 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)

___
*[`src/meta/api/src/schema_api_impl.rs` line 3055 at r2](https://reviewable.io/reviews/databendlabs/databend/16754#-OAvs8JjCY1JhumWMw2q:-OAvs8JjCY1JhumWMw2r:b-azxnra) ([raw file](https://github.com/databendlabs/databend/blob/832601ca4eb65fcdc652dc4a1874b4647a68262a/src/meta/api/src/schema_api_impl.rs#L3055)):*
> ```XML
>                 &req.name_ident,
>                 "rename_dictionary: src (db,dictionary)",
>             )?;
> ```

use  `get_pb().ok_or_else()` would be simple to handle these errors:
```
            let seq_meta = self.get_pb(&tbid).await?.ok_or_else(|| {
                AppError::UnknownTableId(UnknownTableId::new(req.table_id, "create_table_index"))
            })?;
```

https://github.com/datafuselabs/databend/blob/f8201da838d0df1ff00e2213361bdabe128156ef/src/meta/api/src/schema_api_impl.rs#L2447



_Code quote:_
```XML
            let (dict_id_seq, dict_id) = get_u64_value(self, &req.name_ident).await?;
            assert_dictionary_exist(
                dict_id_seq,
                &req.name_ident,
                "rename_dictionary: src (db,dictionary)",
            )?;
```
___
*[`src/meta/api/src/schema_api_impl.rs` line 3058 at r2](https://reviewable.io/reviews/databendlabs/databend/16754#-OAvqTBFEhNk-5A4_0Vn:-OAvqTBFEhNk-5A4_0Vo:biwnno6) ([raw file](https://github.com/databendlabs/databend/blob/832601ca4eb65fcdc652dc4a1874b4647a68262a/src/meta/api/src/schema_api_impl.rs#L3058)):*
> ```XML
> 
>             let new_dict_id_seq = self.get_seq(&req.new_name_ident).await?;
>             dict_has_to_not_exist(new_dict_id_seq, &req.new_name_ident, "rename_dictionary")?;
> ```

This client side assertion does not guarantee there is no such record when it is renamed inside meta-service.

You should have to add a condition to the following `condition` to assert the target record has a zero seq.



_Code quote:_
```XML
            let new_dict_id_seq = self.get_seq(&req.new_name_ident).await?;
            dict_has_to_not_exist(new_dict_id_seq, &req.new_name_ident, "rename_dictionary")?;
```
___
*[`src/meta/api/src/schema_api_impl.rs` line 3511 at r2](https://reviewable.io/reviews/databendlabs/databend/16754#-OAvq4IoD4TTwqhvRmRW:-OAvq4IoD4TTwqhvRmRX:b-v0yb23) ([raw file](https://github.com/databendlabs/databend/blob/832601ca4eb65fcdc652dc4a1874b4647a68262a/src/meta/api/src/schema_api_impl.rs#L3511)):*
> ```XML
>     name_ident: &DictionaryNameIdent,
>     _ctx: impl Display,
> ) -> Result<(), KVAppError> {
> ```

This function should not return KVAppError, it should just return an ExistError.
___
*[`src/meta/api/src/schema_api_test_suite.rs` line 7503 at r2](https://reviewable.io/reviews/databendlabs/databend/16754#-OAvqyBT-hw5L282TUuC:-OAvqyBT-hw5L282TUuD:b-2pdg9r) ([raw file](https://github.com/databendlabs/databend/blob/832601ca4eb65fcdc652dc4a1874b4647a68262a/src/meta/api/src/schema_api_test_suite.rs#L7503)):*
> ```XML
>                 ..DatabaseMeta::default()
>             },
>         };
> ```

Use `Util` to simplify these env setup, refer to:
https://github.com/databendlabs/databend/blob/f8201da838d0df1ff00e2213361bdabe128156ef/src/meta/api/src/schema_api_test_suite.rs#L1093-L1104



_Code quote:_
```XML
        let db1_name = "db1";
        let dict1_name = "dict1";
        let db2_name = "db2";
        let dict2_name = "dict2";

        let db1_req = CreateDatabaseReq {
            create_option: CreateOption::Create,
            name_ident: DatabaseNameIdent::new(&tenant, db1_name),
            meta: DatabaseMeta {
                engine: "".to_string(),
                ..DatabaseMeta::default()
            },
        };
```
___
*[`src/meta/app/src/schema/dictionary.rs` line 180 at r2](https://reviewable.io/reviews/databendlabs/databend/16754#-OAvm_m1EbQu6LrUJiQ7:-OAvm_m1EbQu6LrUJiQ8:bc1zw75) ([raw file](https://github.com/databendlabs/databend/blob/832601ca4eb65fcdc652dc4a1874b4647a68262a/src/meta/app/src/schema/dictionary.rs#L180)):*
> ```XML
> pub struct RenameDictionaryReq {
>     pub name_ident: DictionaryNameIdent,
>     pub new_name_ident: DictionaryNameIdent,
> ```

There should not be another `DictionaryNameIdent`, `DictionaryNameIdent` includes a tenant. But it does not allow to rename to a different tenant. the `new_name_ident` should be just `DictionaryIdentity`. Otherwise the SchemaApi has to check whether the two tenants are the same.
___
*[`src/meta/app/src/schema/dictionary.rs` line 220 at r2](https://reviewable.io/reviews/databendlabs/databend/16754#-OAvnErF0cEIgo64kyb4:-OAvnErF0cEIgo64kyb5:b1px2k5) ([raw file](https://github.com/databendlabs/databend/blob/832601ca4eb65fcdc652dc4a1874b4647a68262a/src/meta/app/src/schema/dictionary.rs#L220)):*
> ```XML
> 
> #[derive(Clone, Debug, PartialEq, Eq)]
> pub struct RenameDictionaryReply {}
> ```

If it is empty. Do not define this type.

**Review by drmingdrmer — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 13 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/databendlabs/databend/16754)* status: 28 of 31 files reviewed, 3 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)

___
*[`src/meta/api/src/schema_api_impl.rs` line 3058 at r2](https://reviewable.io/reviews/databendlabs/databend/16754#-OAvqTBFEhNk-5A4_0Vn:-OB-KbnD72l2I4T55I-4:b14logr) ([raw file](https://github.com/databendlabs/databend/blob/832601ca4eb65fcdc652dc4a1874b4647a68262a/src/meta/api/src/schema_api_impl.rs#L3058)):*
<details><summary><i>Previously, drmingdrmer (张炎泼) wrote…</i></summary><blockquote>

This client side assertion does not guarantee there is no such record when it is renamed inside meta-service.

You should have to add a condition to the following `condition` to assert the target record has a zero seq.
</blockquote></details>

This is not updated yet. If you are going to keep this, please explain the purpose of it.
___
*[`src/meta/api/src/util.rs` line 407 at r4](https://reviewable.io/reviews/databendlabs/databend/16754#-OB-KD3b-_OFypSZOFIm:-OB-KD3b-_OFypSZOFIn:b1ofj1b) ([raw file](https://github.com/databendlabs/databend/blob/5bfb9da5d9c025d0315342616042b14438819209/src/meta/api/src/util.rs#L407)):*
> ```XML
> }
> 
> pub fn assert_dictionary_exist(
> ```

Is this function used at all?

**Review by drmingdrmer — APPROVED** [review]
Nice shot, Thank you!

> Reviewed 1 of 15 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/databendlabs/databend/16754#-:-OB0gWt33KDoCHMUPms3:b-sym18c)* status: all files reviewed, 1 unresolved discussion (waiting on @b41sh and @Winnie-Hong0927)

**Review by b41sh — APPROVED** [review]

**Pull request merged**
