### PR TITLE
feat(query): expand trim/ltrim/rtrim

### PR DESCRIPTION
**Pull request by TCeason**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

support 

```sql
trim(<expr>, expr)
ltrim(<expr>, expr)
rtrim(<expr>, expr)
```

Fix : #16798

## Tests

- [x] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/16802)

### CODE REVIEW

**Comment by TCeason** [comment]
cc @soyeric128 doc need.

**Comment by TCeason** [comment]
> cc @soyeric128 doc need.

Doc also need add     "trim_leading",    "trim_trailing",    "trim_both",

**Review by andylokandy — APPROVED** [review]

**Review by andylokandy — APPROVED** [review]

**Comment by TCeason** [comment]
Please merge this pr. cc @BohuTANG

**Comment by BohuTANG** [comment]
@soyeric128 docs need update, thanks.

**Pull request merged**
