### PR TITLE
feat: short sql length setting

### PR DESCRIPTION
**Pull request by arkzuse**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

New setting for short length sql.

- fixes: #16462 

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/16502)

### CODE REVIEW

**Comment by BohuTANG** [comment]
Hi @arkzuse 

Thanks for the contribution!
This PR is not yet ready for review, so I've converted it to a draft. Please mark it as 'READY' when you believe it's ready for review.

**Comment by arkzuse** [comment]
@BohuTANG sorry for the oversight. What can I do to make it review ready?

**Comment by BohuTANG** [comment]
> @BohuTANG sorry for the oversight. What can I do to make it review ready?

Currently, the settings are only defined. We need to implement them in the `short_sql` func:
https://github.com/datafuselabs/databend/blob/8eaf57b52cc56929291d5d3b25c696c0bd4a2252/src/common/base/src/base/string.rs#L196-L198

Something like `short_sql(sql String, max_length: Usize) ...`

You can refer to other settings for guidance on how to `get` and `set` values.

Finally, please add a test for this PR. Once all tests pass, it will be ready for review, and the tests can reference the other settings.

**Comment by arkzuse** [comment]
@BohuTANG I didn't close it. I am working on this pr and interested to contribute in future.

**Comment by arkzuse** [comment]
Oh i delete my local brach so it close...

**Review by BohuTANG — APPROVED** [review]

**Comment by BohuTANG** [comment]
@arkzuse Thanks for your contribution!

**Pull request merged**
