### PR TITLE
chore(query): query entry display ${USER} and ${PASSWORD}

### PR DESCRIPTION
**Pull request by b41sh**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

query entry remove root user, add `${USER}` and `${PASSWORD}`

- Closes #issue

### CODE REVIEW

**Comment by BohuTANG** [comment]
How to setup a `$USER` and `PASSWORD` when the databend-query server first started?

**Review by sundy-li — APPROVED** [review]

**Comment by sundy-li** [comment]
> How to setup a `$USER` and `PASSWORD` when the databend-query server first started?

The log should not print the real password for security.

**Comment by b41sh** [comment]
> How to setup a `$USER` and `PASSWORD` when the databend-query server first started?

add user and password in the `query.toml` config file

**Comment by BohuTANG** [comment]
We should document how to setup the `user` and `password` config in the documentation, cc @soyeric128

**Pull request merged**
