### PR TITLE
feat(doc): Introducing Databend Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

1.   Introducing Databend Guru on Gurubase.io

Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Databend Guru](https://gurubase.io/g/databend) to Gurubase. Databend Guru uses the data from this repo and data from the [docs](https://docs.databend.com/sql/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Databend Guru", which highlights that Databend now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Databend Guru in Gurubase, just let me know that's totally fine.

## Tests

- [ ] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [x] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [x] Other (please describe): docs

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/16773)

### CODE REVIEW

**Comment by kursataktas** [comment]
Hi again,

Have you had a chance to check this out?

Additionally, I’d like to update you on the release of the Maintainer Panel feature on Gurubase. With this panel, you can add, remove, or update data sources, as well as change the logo and more. You can find the details [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). 

In the near future, I’m planning to include analytics insights in this panel, such as the number of questions asked, the most frequently asked ones, and more. I’ll be sure to update this thread once it’s available. However, in case I miss it, I highly recommend joining our [Discord channel](https://discord.gg/9CMRSQPqx6) to stay updated.

If you’d prefer that I don’t update this thread anymore, please let me know.

**Comment by sundy-li** [comment]
Hi, I have tried gurubase.io  and it looks beneficial.

https://gurubase.io/g/databend/copy-data-from-s3-into-databend

Thank you!

**Comment by sundy-li** [comment]
@kursataktas  Is there a plugin that we can ask `Gurubase` in our own document site ?

**Comment by kursataktas** [comment]
Thanks for the review @sundy-li 

> @kursataktas Is there a plugin that we can ask `Gurubase` in our own document site ?

Currently, it is not available, but we plan to develop this in the near future. I'll update this thread once it becomes available.

**Comment by kursataktas** [comment]
Hey @sundy-li 

Sure! Below, you can find two IDs, one for the main website and the other for the documentation website. Widget IDs are unique to each full domain, including subdomains. They are not secret, so there’s no need to worry about sharing them here, as they only work for requests originating from the associated domain.

For https://www.databend.com
`7-SPtv-tO6nLskN1dc5sZFHrnVlhwx9SAWm8IKFGaoo`

For https://docs.databend.com
`5Qdn4o4C4JVH_fpIy6C9rbtLz94ENT73QtXFVpl6uIM`

You can find instructions on how to install it on the website in this [README](https://github.com/getanteon/gurubase-widget).

I strongly recommend considering maintaining Databend Guru on Gurubase. It’ll make it easier to create, edit, or delete Widget IDs, as well as update or refresh data sources. Plus, we’re planning to release an analytics panel soon, where you’ll be able to see questions users ask and other insights. This can really help shape the product and give you a better understanding of your users.

You can check out the instructions on how to maintain it [here](https://github.com/Gurubase/gurubase?tab=readme-ov-file#how-to-claim-a-guru).

**Comment by kursataktas** [comment]
Hello @sundy-li,

I want to share an exciting update about Gurubase. We've recently released several great features that I think you'll find interesting.

### 1. Slack & Discord Integration
You can now add your Guru as a bot to Slack and Discord, allowing you to ask questions instantly. More details here: [Discord Bot Integration](https://docs.gurubase.ai/integrations/discord-bot).

### 2. Analytics Dashboard
Track what your users ask your Guru and gain valuable insights. This feature is available on the "My Gurus" page. If you haven’t maintained your Guru yet, I highly recommend doing so to access your analytics. More information about claiming your Guru can be found [here](https://github.com/Gurubase/gurubase?tab=readme-ov-file#how-to-claim-a-guru).
image

### 3. API Support
All Guru functionalities are now accessible via API. You can ask questions, edit data sources, and more using our API endpoints. Here is the [API Doc](https://docs.gurubase.ai/api-reference/introduction).

### 4. Codebase Indexing
We now support indexing codebases from GitHub repositories to generate answers for related queries. This feature is available for select Gurus. If you don’t see the "Codebase Indexed" label on your Guru edit page and would like access, please let me know, I’d be happy to enable it for you!
image

Let me know if you have any questions or feedback!

**Pull request merged**
