### PR TITLE
feat: support pushdown predicate into iceberg engine

### LINKED ISSUE #16647: bug: incorrect result of eq expr
**Summary**

```
🐳 :) SELECT 3 = number from numbers(5) where 5 = number;
┌────────────┐
│ 3 = number │
│   Boolean  │
├────────────┤
│ true       │
│ true       │
│ true       │
│ true       │
│ true       │
└────────────┘
5 rows read in 0.019 sec. Processed 5 rows, 40B (263.16 rows/s, 2.06 KiB/s)
```

### PR DESCRIPTION
**Pull request by sundy-li**
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

1. support pushdown filter predicate into iceberg engine
2. fix #16647

## Tests

- [ ] Unit Test
- [x] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/databend/16650)

### CODE REVIEW

**Comment by Xuanwo** [comment]
Thank you for working on this!

**Review by Xuanwo — APPROVED** [review]
Perfect!

**Comment by sundy-li** [comment]
need upgrade iceberg and opendal @Xuanwo

**Comment by Xuanwo** [comment]
> need upgrade iceberg and opendal @Xuanwo

Yep, I will work on this.

**Pull request merged**
