### PR TITLE
feat(planner): Introduce z3-prover to solve constraint

### PR DESCRIPTION
**Pull request by leiysky**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

[Z3](https://github.com/Z3Prover/z3) is an open-source theorem prover developed by Microsoft, usually used to solve SMT problems.

This PR introduces the `z3-rs` library and defines some basic data types and operands.

We can do many things with `z3` in the future, such as simplifying predicates, correctness validation, etc.

### CODE REVIEW

**Comment by Xuanwo** [comment]
Built failed for:

```shell
  CMake Warning at CMakeLists.txt:51 (message):
    Disabling Z3_INCLUDE_GIT_DESCRIBE
  Call Stack (most recent call first):
    CMakeLists.txt:100 (disable_git_describe)


  CMake Warning at CMakeLists.txt:55 (message):
    Disabling Z3_INCLUDE_GIT_HASH
  Call Stack (most recent call first):
    CMakeLists.txt:101 (disable_git_hash)


  CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
  Call Stack (most recent call first):
    /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake-3.18/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:163 (find_package)


  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1
```

cc @everpcpc, can you help take a look? Thanks.

**Comment by leiysky** [comment]
Seems the build environment doesn't have a python installation.
```
--- stderr
  CMake Warning at CMakeLists.txt:51 (message):
    Disabling Z3_INCLUDE_GIT_DESCRIBE
  Call Stack (most recent call first):
    CMakeLists.txt:100 (disable_git_describe)


  CMake Warning at CMakeLists.txt:55 (message):
    Disabling Z3_INCLUDE_GIT_HASH
  Call Stack (most recent call first):
    CMakeLists.txt:101 (disable_git_hash)


  CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
  Call Stack (most recent call first):
    /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake-3.18/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:163 (find_package)


  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1
```

**Comment by leiysky** [comment]
@everpcpc It seems the `python3` installation hasn't been applied to the build image yet, would you mind checking that again? 🥺

**Comment by BohuTANG** [comment]
@mergify update

**Comment by leiysky** [comment]
Seems still need some platform-specific C++ compilers. @everpcpc

**Review by andylokandy — APPROVED** [review]

**Comment by andylokandy** [comment]
Should we add the new tool chain dependencies to makefile?

**Comment by BohuTANG** [comment]
@mergify update

**Comment by BohuTANG** [comment]
musl build still not work @everpcpc

**Comment by everpcpc** [comment]
statefulset failed:
```
08_00_07_list_stage:                                                    [ FAIL ] - result differs with:
--- /runner/_work/databend/databend/tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_07_list_stage.result	2023-04-05 01:48:13.449504100 +0000
+++ /runner/_work/databend/databend/tests/suites/1_stateful/08_select_stage/08_00_parquet/08_00_07_list_stage.stdout	2023-04-05 01:53:17.500825474 +0000
@@ -7,7 +7,7 @@
 --- complex:
 data/complex.parquet	92762	NULL	NULL
 --- limit
-data/tuple.parquet	431	NULL	NULL
+data/complex.parquet	92762	NULL	NULL
 --- where
 data/tuple.parquet	431	NULL	NULL
 --- list files so far
```

**Comment by xudong963** [comment]
@mergify update

**Pull request merged**
